var searchData=
[
  ['callback_5fparams_4',['Callback_Params',['../structMPIcuFFT__Pencil_1_1Callback__Params.html',1,'MPIcuFFT_Pencil&lt; T &gt;::Callback_Params'],['../structMPIcuFFT__Pencil__Opt1_1_1Callback__Params.html',1,'MPIcuFFT_Pencil_Opt1&lt; T &gt;::Callback_Params'],['../structMPIcuFFT__Slab_1_1Callback__Params.html',1,'MPIcuFFT_Slab&lt; T &gt;::Callback_Params'],['../structMPIcuFFT__Slab__Opt1_1_1Callback__Params.html',1,'MPIcuFFT_Slab_Opt1&lt; T &gt;::Callback_Params'],['../structMPIcuFFT__Slab__Y__Then__ZX_1_1Callback__Params.html',1,'MPIcuFFT_Slab_Y_Then_ZX&lt; T &gt;::Callback_Params'],['../structMPIcuFFT__Slab__Z__Then__YX_1_1Callback__Params.html',1,'MPIcuFFT_Slab_Z_Then_YX&lt; T &gt;::Callback_Params'],['../structMPIcuFFT__Slab__Z__Then__YX__Opt1_1_1Callback__Params.html',1,'MPIcuFFT_Slab_Z_Then_YX_Opt1&lt; T &gt;::Callback_Params']]],
  ['callback_5fparams_5fbase_5',['Callback_Params_Base',['../structMPIcuFFT__Pencil_1_1Callback__Params__Base.html',1,'MPIcuFFT_Pencil&lt; T &gt;::Callback_Params_Base'],['../structMPIcuFFT__Pencil__Opt1_1_1Callback__Params__Base.html',1,'MPIcuFFT_Pencil_Opt1&lt; T &gt;::Callback_Params_Base'],['../structMPIcuFFT__Slab_1_1Callback__Params__Base.html',1,'MPIcuFFT_Slab&lt; T &gt;::Callback_Params_Base'],['../structMPIcuFFT__Slab__Opt1_1_1Callback__Params__Base.html',1,'MPIcuFFT_Slab_Opt1&lt; T &gt;::Callback_Params_Base'],['../structMPIcuFFT__Slab__Y__Then__ZX_1_1Callback__Params__Base.html',1,'MPIcuFFT_Slab_Y_Then_ZX&lt; T &gt;::Callback_Params_Base'],['../structMPIcuFFT__Slab__Z__Then__YX_1_1Callback__Params__Base.html',1,'MPIcuFFT_Slab_Z_Then_YX&lt; T &gt;::Callback_Params_Base'],['../structMPIcuFFT__Slab__Z__Then__YX__Opt1_1_1Callback__Params__Base.html',1,'MPIcuFFT_Slab_Z_Then_YX_Opt1&lt; T &gt;::Callback_Params_Base']]],
  ['commorder_5ffirsttranspose_6',['commOrder_FirstTranspose',['../classMPIcuFFT__Pencil.html#a33f9899860e7a40807ac343b51dde4ad',1,'MPIcuFFT_Pencil']]],
  ['commorder_5fsecondtranspose_7',['commOrder_SecondTranspose',['../classMPIcuFFT__Pencil.html#ad0ee0a3efe38fc4885c63c23a56b53ec',1,'MPIcuFFT_Pencil']]],
  ['configurations_8',['Configurations',['../structConfigurations.html',1,'']]],
  ['cuda_5faware_9',['cuda_aware',['../classTests__Reference.html#a0a1c9fb52c2ba294179aff1ad5a5156e',1,'Tests_Reference']]],
  ['cufft_10',['cuFFT',['../structcuFFT.html',1,'']]],
  ['cufft_3c_20double_20_3e_11',['cuFFT&lt; double &gt;',['../structcuFFT_3_01double_01_4.html',1,'']]]
];
